Use mkv container and srt subtitle format for video if using --subs-embed
This is required so that videos can be created on stock Fedora,
which lacks support for mov_text subtitle codec required for mp4.

Note that the mkv format is not tagged, as atomic parsley doesn't
support it.

The error message this fixes is the following:
        INFO: Converting to MP4 and embedding subtitles
        [sost#0:2 @ 0x5579ba7597c0] Unknown encoder 'mov_text'
        [sost#0:2 @ 0x5579ba7597c0] Error selecting an encoder
        Error opening output files: Encoder not found
        INFO: Command exit code 8 (raw code = 2048)
        ERROR: Conversion failed - retaining video file: ...